{% set name = "socat" %}
{% set version = "1.7.4.2" %}
{% set sha256 = "6690a9f9990457b505097a272bbf2cbf4cc35576176f76646e3524b0e91c1763" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://www.dest-unreach.org/{{ name }}/download/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  #patches:
  #  - 0001-use-speed_t.patch  # [osx]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - openssl
    - readline
  run:
    - openssl
    - readline

test:
  commands:
    - filan -h
    - procan -h
    - socat -h

about:
  home: http://www.dest-unreach.org/socat/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A relay for bidirectional transfer between data channels (netcat++)

  # The remaining entries in this section are optional, but recommended
  description: |
    socat is a relay for bidirectional data transfer between two independent data
    channels. Each of these data channels may be a file, pipe, device (serial line
    etc. or a pseudo terminal), a socket (UNIX, IP4, IP6 - raw, UDP, TCP), an
    SSL socket, proxy CONNECT connection, a file descriptor (stdin etc.), the GNU
    line editor (readline), a program, or a combination of two of these.
    These modes include generation of "listening" sockets, named pipes, and pseudo
    terminals.

    socat can be used, e.g., as TCP port forwarder (one-shot or daemon), as an
    external socksifier, for attacking weak firewalls, as a shell interface to UNIX
    sockets, IP6 relay, for redirecting TCP oriented programs to a serial line, to
    logically connect serial lines on different computers, or to establish a
    relatively secure environment (su and  chroot) for running client or server
    shell scripts with network connections.
  doc_url: http://www.dest-unreach.org/socat/doc/README
  dev_url: http://repo.or.cz/r/socat.git

extra:
  recipe-maintainers:
    - sodre
