travis:
  secure:
    BINSTAR_TOKEN: PurcJ4Yvp8w9PyuOtncUnVgyXNWPh1puwonqjvxi8PApF2ZT6DG/zxjdFwyJ2Qx6Z7umdH1hEq3uNBh/nL0/ZGKS3aous59+an4jDNyc7udM6IkaIzw+QesunqEpTXsUJDBwIUqNL3TEXjis8fAVLKpviUQwZQKodJDfssy618TzlrCxaHCArFqULxb27tkg1uRHKMkYJnKIRQygQoycBYnXtHXOZht0udxoPtYRaLAAiBATpBncucQUhzgOGfQUw2in7olu9lj+iwQaftV6Antp1U+GSXksMweWRJXxdi+RQhne20xbn+VUswapvVpH0gKhVFW6gxzDDC5D4kZBEyhNZYORM7bLHJo3rX1qu9FBv3OatW6o2smiQMi4x74daxZLKm+cXEvzGZsAWAtc3ciGx25Zd9DtKfPSBEgOT2rgijRDKFrrOJHm+3x1s8Da7tufrsYh9eQQJf2zyXjeTjppevQB+zHYwIFXTXl0d0ceXAgNCDamwg/dg1LGMluMRlftP+kPpUJe016pDIeJdHDqV3XNZjZyviwq2h62iczYRw8dUzixhnIhkS9uSyR1niwF844LNWzAqufOgAcusQ8iT+M6jZfRE6ZP+E/LjowMFWiH5Jb/5fmoujqIJL5tbYO9mdJUvSclp3j6u1maHPCX9dDwWMfbGpc9ITY1bBc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
