appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hBSkCbZ3eXPTN3hQ9knmTp0g+S2Xb/GgU0o1Pa7buGUhzQ2e2ea7MYzqhpPItjOIZyLNHb+n26BfFQ22YCH+hcpKqFVZeBUzwPBDqNHm+/bF8XJTRqnFqhxZWpKmS7qxhm/gp8PmKwPL2ghEeInvYtqCzCuKSQjWN7j+1hqd5kYPCozpsJKKhOR+N48rxiuJX8mI40SFq67HOcr58th+pqZFtqbQnKikVewSI/ubJyN6IaEMC9Zll33hblSrYugEzZTYqcsyg4FAp5lenqawDXBm0X8QrsU++xqkvclUmDIRsUIxz4RS5IANmQfC949xR0vOhJxBFGdrZHv58YhU8OuiODd3zVBWJuJl33Mi/wIRrxL7m+ENjLsDCJREIenDPwbwm4x7UaOMiwOsvZklS6oyDlMC+9Qz4oDr9E9TrwSuDmU0h+DolAMx/DYKhM8tcRJbxyleMOJY9SiEzp3jqlBRSjjZdMReWZnFcbJogN5/gZucg2pwO8IBT4I4xVFl4S/67QWNuYKzWa16C8pyTvnixZVsj1AJstFcj/114WKKfkeuF3ki6cxvhaFw837uf1D3lKaosVw9gVz+BAPF99k8BtdZvuvt6oSs6+/JhVPtvp/4ogghrJCiosfP0zeoPcp2Uud5pfTEhy7JZpQUR0nK/YdeH1r7w6uaDU+m86U=}
conda_forge_output_validation: false
